defaults:
  issuesLimit: 20
  notificationsLimit: 20
  prApproveComment: LGTM
  preview:
    open: true
    width: 0.50
    height: 0.89
    position: auto
  prsLimit: 20
  refetchIntervalMinutes: 30
  view: prs
keybindings:
  prs:
    - key: d
      name: tuicr diff
      command: tuicr pr {{.RepoName}}#{{.PrNumber}}
theme:
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#89b4fa"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f9e2af"
      success: "#a6e3a1"
      error: "#f38ba8"
    background:
      selected: "#313244"
    border:
      primary: "#89b4fa"
      secondary: "#45475a"
      faint: "#313244"
