name: test

on:
  push:
    branches:
      - master
      - 'develop-**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.9.0
    steps:
    - uses: actions/checkout@v3
    - name: Run shellcheck
      run: shellcheck -s bash -f tty ./bin/xpanes ./*.sh

  shfmt:
    runs-on: ubuntu-latest
    container: mvdan/shfmt:v3.1.0-alpine
    steps:
    - uses: actions/checkout@v3
    - name: Run shfmt
      run: shfmt -i 2 -ci -sr -kp -d ./bin/xpanes ./*.sh

  test:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    container: bash:${{matrix.bash}}
    strategy:
      matrix:
        include:
###START_INSERT###
          - bash: "3.2"
            tmux: "1.8"
            cases: 2,6,14,41
          - bash: "3.2"
            tmux: "1.9"
            cases: 2,21,52,85
          - bash: "3.2"
            tmux: "1.9a"
            cases: 4,5,6,13,20,45,79
          - bash: "3.2"
            tmux: "2.0"
            cases: 13,24,29,31,33,39,41,43,45,47,56,70,76,78,80
          - bash: "3.2"
            tmux: "2.1"
            cases: 23,33,44,45,50,55,61
          - bash: "3.2"
            tmux: "2.2"
            cases: 10,18,24,62,81
          - bash: "3.2"
            tmux: "2.3"
            cases: 12,13,20,36,45,60,82,85
          - bash: "3.2"
            tmux: "2.4"
            cases: 16,20,27,36,51,66,70,81,82,86
          - bash: "3.2"
            tmux: "2.5"
            cases: 8,14,26,44,49,72
          - bash: "3.2"
            tmux: "2.6"
            cases: 10,17,21,22,48,56,59,66,77,79
          - bash: "3.2"
            tmux: "2.7"
            cases: 1,20,29,44,58,62,64,68,74,78,81,82,87
          - bash: "3.2"
            tmux: "2.8"
            cases: 5,36,40,43,47,49,59,69,71,74,84
          - bash: "3.2"
            tmux: "2.9"
            cases: 1,4,7,9,15,20,21,26,32,35,38,65,72
          - bash: "3.2"
            tmux: "2.9a"
            cases: 2,8,11,30,32,37,39,52,53,60,67,70,86
          - bash: "3.2"
            tmux: "3.0a"
            cases: 3,12,16,22,23,24,35,38,52,63,68,81
          - bash: "3.2"
            tmux: "3.1"
            cases: 20,22,34,39,58,61,77
          - bash: "3.2"
            tmux: "3.1b"
            cases: 20,44,46,58,71,75,78,88
          - bash: "3.2"
            tmux: "3.1c"
            cases: 15,26,28,40,42,58,73,82,83,85,87
          - bash: "3.2"
            tmux: "3.2"
            cases: 2,19,23,24,25,28,54,56,57,65,80,85
          - bash: "3.2"
            tmux: "3.3a"
            cases: 26,32,39,40,63,68,69,79
          - bash: "4.0"
            tmux: "1.8"
            cases: 8,25,33,37,46,88
          - bash: "4.0"
            tmux: "1.9"
            cases: 4,18,19,24,38,55,68,77,80,83
          - bash: "4.0"
            tmux: "1.9a"
            cases: 14,26,28,30,31,42,58,72,88
          - bash: "4.0"
            tmux: "2.0"
            cases: 3,8,32,42,50,62,77,87
          - bash: "4.0"
            tmux: "2.1"
            cases: 6,17,21,25,42,64,77,88
          - bash: "4.0"
            tmux: "2.2"
            cases: 27,29,43,49,52,71,72,83
          - bash: "4.0"
            tmux: "2.3"
            cases: 10,21,33,41,69,70,80,83,87,88
          - bash: "4.0"
            tmux: "2.4"
            cases: 28,38,40,56,76,87
          - bash: "4.0"
            tmux: "2.5"
            cases: 1,3,21,33,38,51,54,57,76
          - bash: "4.0"
            tmux: "2.6"
            cases: 1,4,35,46,53,60,63,68,70,73,75,86
          - bash: "4.0"
            tmux: "2.7"
            cases: 2,15,23,25,41,56,71,84,88
          - bash: "4.0"
            tmux: "2.8"
            cases: 1,20,39,45,50
          - bash: "4.0"
            tmux: "2.9"
            cases: 11,36,40,46,67,68
          - bash: "4.0"
            tmux: "2.9a"
            cases: 18,19,24,36,38,43,44,49,62,74,78,81,83
          - bash: "4.0"
            tmux: "3.0a"
            cases: 7,14,41,47,59,70,78,84
          - bash: "4.0"
            tmux: "3.1"
            cases: 5,9,10,26,27,43,72,74,79
          - bash: "4.0"
            tmux: "3.1b"
            cases: 2,9,10,13,15,31,47,48,52,85,86
          - bash: "4.0"
            tmux: "3.1c"
            cases: 10,12,13,16,20,30,36,43,51,52,62,76
          - bash: "4.0"
            tmux: "3.2"
            cases: 1,22,34,39,48,51,61,79,83,88
          - bash: "4.0"
            tmux: "3.3a"
            cases: 11,14,22,30,36,44,57,60,65,66,72,82,87
          - bash: "4.1"
            tmux: "1.8"
            cases: 17,27,39,71,76,78,79,80,87
          - bash: "4.1"
            tmux: "1.9"
            cases: 6,12,14,36,43,48,70,84,87
          - bash: "4.1"
            tmux: "1.9a"
            cases: 2,10,18,33,41,50,64,78,87
          - bash: "4.1"
            tmux: "2.0"
            cases: 4,11,18,38,44,52,68,72,83
          - bash: "4.1"
            tmux: "2.1"
            cases: 1,8,12,13,15,16,18,34,35,40,47,48,51,56,72,81
          - bash: "4.1"
            tmux: "2.2"
            cases: 23,33,40,41,50,55,61,68,86
          - bash: "4.1"
            tmux: "2.3"
            cases: 14,15,37,46,55,71,79
          - bash: "4.1"
            tmux: "2.4"
            cases: 7,9,11,21,24,31,32,37,48,50,62,67
          - bash: "4.1"
            tmux: "2.5"
            cases: 4,9,10,32,34,45,47,64,83,84
          - bash: "4.1"
            tmux: "2.6"
            cases: 14,24,27,36,38,47,55,62,65,76,78
          - bash: "4.1"
            tmux: "2.7"
            cases: 5,10,16,22,30,46,51,52,60,67,69
          - bash: "4.1"
            tmux: "2.8"
            cases: 7,15,37,60,73,85
          - bash: "4.1"
            tmux: "2.9"
            cases: 3,5,8,33,39,42,58,70,75,77,85
          - bash: "4.1"
            tmux: "2.9a"
            cases: 1,4,14,26,28,31,47,54,88
          - bash: "4.1"
            tmux: "3.0a"
            cases: 19,30,46,54,57,67,77,79,82,86
          - bash: "4.1"
            tmux: "3.1"
            cases: 37,48,49,53,59,68,78,80,84
          - bash: "4.1"
            tmux: "3.1b"
            cases: 3,7,24,29,32,59,61,70,77,79,81
          - bash: "4.1"
            tmux: "3.1c"
            cases: 4,17,19,25,27,38,54,66,70,72,77
          - bash: "4.1"
            tmux: "3.2"
            cases: 6,12,13,44,63,74
          - bash: "4.1"
            tmux: "3.3a"
            cases: 4,5,6,8,17,20,35,49,55,67,80
          - bash: "4.2"
            tmux: "1.8"
            cases: 4,11,19,20,21,28,29,61,72,86
          - bash: "4.2"
            tmux: "1.9"
            cases: 8,9,17,25,37,45,51,57,62,81
          - bash: "4.2"
            tmux: "1.9a"
            cases: 1,17,19,24,48,52,82
          - bash: "4.2"
            tmux: "2.0"
            cases: 5,6,7,20,30,35,37,54,85
          - bash: "4.2"
            tmux: "2.1"
            cases: 7,39,43,76,80
          - bash: "4.2"
            tmux: "2.2"
            cases: 3,9,13,20,30,51,57,85
          - bash: "4.2"
            tmux: "2.3"
            cases: 6,16,17,28,30,58,59
          - bash: "4.2"
            tmux: "2.4"
            cases: 2,8,30,33,35,46
          - bash: "4.2"
            tmux: "2.5"
            cases: 2,5,18,22,58,67,70,78,81
          - bash: "4.2"
            tmux: "2.6"
            cases: 7,11,12,15,31,32,34,37,44,50,64,74,84
          - bash: "4.2"
            tmux: "2.7"
            cases: 14,18,35,38,40,48,57,79,85
          - bash: "4.2"
            tmux: "2.8"
            cases: 13,27,31,33,51,62,67,75,82,83,87
          - bash: "4.2"
            tmux: "2.9"
            cases: 22,24,30,34,43,44,48,52,53,63,80,82
          - bash: "4.2"
            tmux: "2.9a"
            cases: 10,23,29,40,71,77,80,85
          - bash: "4.2"
            tmux: "3.0a"
            cases: 17,44,45,53,60,72,73
          - bash: "4.2"
            tmux: "3.1"
            cases: 6,7,12,36,41,50,55,56,71,87,88
          - bash: "4.2"
            tmux: "3.1b"
            cases: 1,5,6,22,68,72,83
          - bash: "4.2"
            tmux: "3.1c"
            cases: 14,22,37,45,46,55,61,64,65,78,80
          - bash: "4.2"
            tmux: "3.2"
            cases: 14,26,42,46,49,53,66,68,69,76,77,78
          - bash: "4.2"
            tmux: "3.3a"
            cases: 16,19,21,27,41,42,47,59,75,81,84
          - bash: "4.3"
            tmux: "1.8"
            cases: 36,38,42,43,44,62,68,70
          - bash: "4.3"
            tmux: "1.9"
            cases: 7,22,23,29,32,39,41,44,53
          - bash: "4.3"
            tmux: "1.9a"
            cases: 15,38,43,44,46,47,55,61,71,84
          - bash: "4.3"
            tmux: "2.0"
            cases: 1,15,19,23,51
          - bash: "4.3"
            tmux: "2.1"
            cases: 4,11,20,29,30,31,41,49,54,58,65,78
          - bash: "4.3"
            tmux: "2.2"
            cases: 1,4,8,16,32,35,56,65,69,70
          - bash: "4.3"
            tmux: "2.3"
            cases: 7,26,29,32,48,65,76,77
          - bash: "4.3"
            tmux: "2.4"
            cases: 22,25,57,60,77
          - bash: "4.3"
            tmux: "2.5"
            cases: 40,46,52,53,62,66,77,86,87
          - bash: "4.3"
            tmux: "2.6"
            cases: 5,6,23,28,39,57,67,69,71,82,87
          - bash: "4.3"
            tmux: "2.7"
            cases: 3,6,8,9,13,34,39,43,50
          - bash: "4.3"
            tmux: "2.8"
            cases: 11,12,24,41,52,58,72,81,88
          - bash: "4.3"
            tmux: "2.9"
            cases: 10,14,23,31,50,55,64,73,83,88
          - bash: "4.3"
            tmux: "2.9a"
            cases: 6,7,9,15,17,22,25,27,35,45,63,73,75,87
          - bash: "4.3"
            tmux: "3.0a"
            cases: 2,32,33,34,58,62,80
          - bash: "4.3"
            tmux: "3.1"
            cases: 21,24,35,47,63,67
          - bash: "4.3"
            tmux: "3.1b"
            cases: 12,26,28,36,37,41,42,45,69,74
          - bash: "4.3"
            tmux: "3.1c"
            cases: 9,33,39,49,59,79,86
          - bash: "4.3"
            tmux: "3.2"
            cases: 3,17,21,27,35,37,40,45,52,71,87
          - bash: "4.3"
            tmux: "3.3a"
            cases: 1,3,13,18,31,50,77,85,86
          - bash: "4.4"
            tmux: "1.8"
            cases: 7,26,40,64,69
          - bash: "4.4"
            tmux: "1.9"
            cases: 1,5,15,20,27,49,50,54,58,65,71,79,86,88
          - bash: "4.4"
            tmux: "1.9a"
            cases: 8,11,22,51,53,54,56,83
          - bash: "4.4"
            tmux: "2.0"
            cases: 14,16,17,21,34,36,53,69,71,79,84
          - bash: "4.4"
            tmux: "2.1"
            cases: 2,24,38,52,53,62,71,87
          - bash: "4.4"
            tmux: "2.2"
            cases: 6,11,31,39,42,45,64,84
          - bash: "4.4"
            tmux: "2.3"
            cases: 3,23,27,35,40,43,47,64,66
          - bash: "4.4"
            tmux: "2.4"
            cases: 4,5,10,12,15,44,49,64,78,79,85
          - bash: "4.4"
            tmux: "2.5"
            cases: 12,17,23,39,48,50,55,60
          - bash: "4.4"
            tmux: "2.6"
            cases: 2,19,29,30,33,45,51,72,81,85,88
          - bash: "4.4"
            tmux: "2.7"
            cases: 21,33,37,49,54,59,65,70,77,83
          - bash: "4.4"
            tmux: "2.8"
            cases: 3,26,28,29,38,46,48,57,61,63,65,68,80
          - bash: "4.4"
            tmux: "2.9"
            cases: 2,13,17,19,28,45,51,86,87
          - bash: "4.4"
            tmux: "2.9a"
            cases: 3,20,51,55,58,59,65,66,68,69,76,82
          - bash: "4.4"
            tmux: "3.0a"
            cases: 9,10,15,18,21,25,26,37,61,69
          - bash: "4.4"
            tmux: "3.1"
            cases: 4,11,14,23,31,38,42,54,75,76,81
          - bash: "4.4"
            tmux: "3.1b"
            cases: 4,8,11,19,39,50,55,57,60,62,73,82
          - bash: "4.4"
            tmux: "3.1c"
            cases: 11,41,74,75
          - bash: "4.4"
            tmux: "3.2"
            cases: 10,16,30,31,32,43,59,67,82
          - bash: "4.4"
            tmux: "3.3a"
            cases: 15,29,34,43,51,53,56,58,62,71,76
          - bash: "5.0"
            tmux: "1.8"
            cases: 3,9,22,24,34,45,47,55,57,83,85
          - bash: "5.0"
            tmux: "1.9"
            cases: 3,10,30,33,34,40,42,56,64,78
          - bash: "5.0"
            tmux: "1.9a"
            cases: 3,9,12,25,27,29,34,35,39,49,62,65,77,80,81,86
          - bash: "5.0"
            tmux: "2.0"
            cases: 9,10,28,46,55,61,64,65,81,88
          - bash: "5.0"
            tmux: "2.1"
            cases: 19,22,32,57,85,86
          - bash: "5.0"
            tmux: "2.2"
            cases: 2,7,14,17,19,21,22,28,37,46,47,58,76,79,88
          - bash: "5.0"
            tmux: "2.3"
            cases: 2,4,18,25,31,39,44,78
          - bash: "5.0"
            tmux: "2.4"
            cases: 1,6,53,59,71,88
          - bash: "5.0"
            tmux: "2.5"
            cases: 11,15,16,25,27,31,42,65,69,80,82
          - bash: "5.0"
            tmux: "2.6"
            cases: 16,25,42,80,83
          - bash: "5.0"
            tmux: "2.7"
            cases: 26,47,53,72
          - bash: "5.0"
            tmux: "2.8"
            cases: 8,9,14,54,56,86
          - bash: "5.0"
            tmux: "2.9"
            cases: 29,41,56,61,66,74,78,81,84
          - bash: "5.0"
            tmux: "2.9a"
            cases: 12,16,50,56,84
          - bash: "5.0"
            tmux: "3.0a"
            cases: 5,6,8,13,36,50,56,66,71,76,85
          - bash: "5.0"
            tmux: "3.1"
            cases: 3,8,13,17,30,40,46,51,52,57,60,83
          - bash: "5.0"
            tmux: "3.1b"
            cases: 14,16,23,27,30,33,40,43,53,66,76,87
          - bash: "5.0"
            tmux: "3.1c"
            cases: 1,2,24,48,53,60,63,67,68
          - bash: "5.0"
            tmux: "3.2"
            cases: 8,20,41,62,73,75
          - bash: "5.0"
            tmux: "3.3a"
            cases: 7,28,38,54,61,64,70,88
          - bash: "5.1"
            tmux: "1.8"
            cases: 10,13,16,23,35,48,77,81
          - bash: "5.1"
            tmux: "1.9"
            cases: 16,31,72,76
          - bash: "5.1"
            tmux: "1.9a"
            cases: 7,16,21,23,32,68,69,85
          - bash: "5.1"
            tmux: "2.0"
            cases: 2,22,25,26,40,49,57,86
          - bash: "5.1"
            tmux: "2.1"
            cases: 3,5,9,14,26,27,28,36,46,68,79
          - bash: "5.1"
            tmux: "2.2"
            cases: 5,12,25,38,48,54,77,78,82
          - bash: "5.1"
            tmux: "2.3"
            cases: 11,22,24,34,38,57,72
          - bash: "5.1"
            tmux: "2.4"
            cases: 13,17,23,26,29,34,39,41,42,52,65,80,83
          - bash: "5.1"
            tmux: "2.5"
            cases: 6,19,28,30,41,43,79,88
          - bash: "5.1"
            tmux: "2.6"
            cases: 3,18,20,26,40,49,54,58
          - bash: "5.1"
            tmux: "2.7"
            cases: 7,11,12,19,24,27,32,63,73,80
          - bash: "5.1"
            tmux: "2.8"
            cases: 4,6,10,16,17,19,21,35,44,53,55,66,70,76
          - bash: "5.1"
            tmux: "2.9"
            cases: 18,25,27,37,59,60,62,69,71
          - bash: "5.1"
            tmux: "2.9a"
            cases: 5,13,34,57,61,72,79
          - bash: "5.1"
            tmux: "3.0a"
            cases: 1,4,11,20,28,29,42,64,65,74,75,83,87
          - bash: "5.1"
            tmux: "3.1"
            cases: 2,15,18,19,28,29,44,65,66,82
          - bash: "5.1"
            tmux: "3.1b"
            cases: 17,21,38,49,51,54,56,67,80,84
          - bash: "5.1"
            tmux: "3.1c"
            cases: 7,8,23,31,34,44,47,50,56,88
          - bash: "5.1"
            tmux: "3.2"
            cases: 9,11,15,29,33,47,64,70,86
          - bash: "5.1"
            tmux: "3.3a"
            cases: 24,37,45,46,48,73
          - bash: "5.2"
            tmux: "1.8"
            cases: 12,15,18,30,58,65,82
          - bash: "5.2"
            tmux: "1.9"
            cases: 11,13,26,28,35,46,47,61,69,82
          - bash: "5.2"
            tmux: "1.9a"
            cases: 36,37,40,57,70,76
          - bash: "5.2"
            tmux: "2.0"
            cases: 12,27,48,58,82
          - bash: "5.2"
            tmux: "2.1"
            cases: 10,37,69,70,82,83,84
          - bash: "5.2"
            tmux: "2.2"
            cases: 15,26,34,36,44,53,80,87
          - bash: "5.2"
            tmux: "2.3"
            cases: 8,9,19,42,67,68,81,86
          - bash: "5.2"
            tmux: "2.4"
            cases: 3,14,18,19,43,45,47,54,55,58,68,69,72,84
          - bash: "5.2"
            tmux: "2.5"
            cases: 7,13,20,24,29,35,36,37,56,59,68,71,85
          - bash: "5.2"
            tmux: "2.6"
            cases: 8,9,13,41,43,52
          - bash: "5.2"
            tmux: "2.7"
            cases: 4,17,28,31,36,42,45,55,66,75,76,86
          - bash: "5.2"
            tmux: "2.8"
            cases: 2,18,22,23,25,30,32,34,42,64,77,78,79
          - bash: "5.2"
            tmux: "2.9"
            cases: 6,12,16,47,49,54,57,76,79
          - bash: "5.2"
            tmux: "2.9a"
            cases: 21,33,41,42,46,48,64
          - bash: "5.2"
            tmux: "3.0a"
            cases: 27,31,39,40,43,48,49,51,55,88
          - bash: "5.2"
            tmux: "3.1"
            cases: 1,16,25,32,33,45,62,64,69,70,73,85,86
          - bash: "5.2"
            tmux: "3.1b"
            cases: 18,25,34,35,63,64,65
          - bash: "5.2"
            tmux: "3.1c"
            cases: 3,5,6,18,21,29,32,35,57,69,71,81,84
          - bash: "5.2"
            tmux: "3.2"
            cases: 4,5,7,18,36,38,50,55,58,60,72,81,84
          - bash: "5.2"
            tmux: "3.3a"
            cases: 2,9,10,12,23,25,33,52,74,78,83
###END_INSERT###

    steps:
    - uses: actions/checkout@v3
    - name: Install dependency
      run: |
        apk add make curl gcc musl-dev libevent-dev ncurses-dev perl git util-linux bsd-compat-headers
        git clone -b v2.1.8 https://github.com/kward/shunit2.git test/shunit2

    - name: Install tmux
      run: |
        curl -L "https://github.com/tmux/tmux/releases/download/${{matrix.tmux}}/tmux-${{matrix.tmux}}.tar.gz" | tar zxv
        cd tmux-${{matrix.tmux}}
        ./configure
        make
        make install
        printf "set-window-option -g automatic-rename off\nset-option -g allow-rename off\n" >> "$HOME/.tmux.conf"

    - name: Unit test
      run: |
        script -e -c /bin/bash -c 'TERM=xterm bash ./test/unit.sh'

    - name: Scenario test
      run: |
        bash ./test/test_generator.sh ${{matrix.cases}} > ./test/cases_pairwise.sh
        script -e -c /bin/bash -c 'stty rows 40 cols 80;TERM=xterm bash ./test/cases_pairwise.sh'
